[pytest]
DJANGO_SETTINGS_MODULE = FinGest.test_settings
python_files = test_*.py
norecursedirs = .git __pycache__ migrations static docs
addopts = --ignore=gestion_financiera_basica/test_views.py --cov=. --cov-report=xml:coverage.xml --cov-report=term-missing
