sonar.projectKey=nickSPE_acevedo
sonar.organization=nickSPE
sonar.projectName=Fingest
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/migrations/**,**/static/**,**/__pycache__/**,**/test/**,**/docs/**
sonar.tests=test/
sonar.test.inclusions=**/test*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.language=py
