# Generated by Django 5.2 on 2025-07-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_default', models.CharField(default='mes_actual', max_length=20)),
                ('incluir_subcuentas_inactivas', models.BooleanField(default=False)),
                ('formato_export_default', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('moneda_display', models.CharField(default='USD', max_length=10)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('gastos_categoria', 'Gastos por Categoría'), ('ingresos_egresos', 'Ingresos vs Egresos'), ('subcuentas_analisis', 'Análisis de Subcuentas'), ('balance_general', 'Balance General'), ('flujo_efectivo', 'Flujo de Efectivo')], max_length=25)),
                ('titulo', models.CharField(default='Reporte Financiero', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
