<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-30 15:11

=======
# Generated by Django 5.2.1 on 2025-06-10 21:17

import django.db.models.deletion
>>>>>>> bba8140 (Corrige problemas con migraciones)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('cuentas', '0001_initial'),
>>>>>>> bba8140 (Corrige problemas con migraciones)
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=25)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
<<<<<<< HEAD
=======
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
>>>>>>> bba8140 (Corrige problemas con migraciones)
            ],
        ),
    ]
