# Generated by Django 5.2 on 2025-07-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('saldo_cuenta', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tipo', models.CharField(choices=[('emergencia', 'Emergencia'), ('objetivos', 'Objetivos'), ('inversion', 'Inversión'), ('gastos', 'Gastos'), ('ahorro', 'Ahorro'), ('entretenimiento', 'Entretenimiento'), ('transporte', 'Transporte'), ('alimentacion', 'Alimentación'), ('salud', 'Salud'), ('educacion', 'Educación'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaSubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
