# Generated by Django 5.2.1 on 2025-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('saldo_cuenta', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la subcuenta', max_length=50)),
                ('descripcion', models.CharField(blank=True, help_text='Propósito y objetivo de esta subcuenta', max_length=300, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual en la subcuenta', max_digits=15)),
                ('tipo', models.CharField(choices=[('tienda_online', 'Tienda Online'), ('tienda_fisica', 'Tienda Física'), ('servicios_profesionales', 'Servicios Profesionales'), ('freelance', 'Trabajo Freelance'), ('negocio_propio', 'Negocio Propio'), ('ingresos_pasivos', 'Ingresos Pasivos'), ('ventas_productos', 'Ventas de Productos'), ('consultoria', 'Consultoría'), ('alquiler_propiedades', 'Alquiler de Propiedades'), ('ahorro_meta', 'Ahorro para Meta'), ('emergencia', 'Fondo de Emergencia'), ('inversion', 'Inversiones'), ('gastos_fijos', 'Gastos Fijos'), ('gastos_variables', 'Gastos Variables'), ('entretenimiento', 'Entretenimiento'), ('viajes', 'Viajes y Vacaciones'), ('educacion', 'Educación y Cursos'), ('salud', 'Salud y Bienestar'), ('familia', 'Gastos Familiares'), ('otros', 'Otros')], default='otros', help_text='Categoría de la subcuenta', max_length=30)),
                ('color', models.CharField(default='#3B82F6', help_text='Color para identificación visual', max_length=7)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la subcuenta está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_negocio', models.BooleanField(default=False, help_text='Marca si es una subcuenta de negocio')),
                ('meta_objetivo', models.DecimalField(blank=True, decimal_places=2, help_text='Meta de ahorro u objetivo financiero', max_digits=15, null=True)),
                ('fecha_meta', models.DateField(blank=True, help_text='Fecha límite para alcanzar la meta', null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaCuentaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito hacia cuenta principal'), ('retiro', 'Retiro hacia subcuenta')], default='deposito', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaSubCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
