# Generated by Django 5.2.1 on 2025-11-25 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SUBCUENTA_MODEL = 'cuentas.subcuenta'


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='id_cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta principal (opcional para subcuentas independientes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Propietario directo (requerido para subcuentas independientes)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciacuentaprincipal',
            name='cuenta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_desde_subcuentas', to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='transferenciacuentaprincipal',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciacuentaprincipal',
            name='subcuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_cuenta_principal', to=SUBCUENTA_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciasubcuenta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciasubcuenta',
            name='subcuenta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to=SUBCUENTA_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciasubcuenta',
            name='subcuenta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=SUBCUENTA_MODEL),
        ),
    ]
