# Generated by Django 5.2 on 2025-07-06 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='transferenciasubcuenta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciasubcuenta',
            name='subcuenta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='cuentas.subcuenta'),
        ),
        migrations.AddField(
            model_name='transferenciasubcuenta',
            name='subcuenta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='cuentas.subcuenta'),
        ),
    ]
