# Generated by Django 5.2 on 2025-07-06 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subcuenta',
            name='es_negocio',
            field=models.BooleanField(default=False, help_text='Marca si es una subcuenta de negocio'),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='fecha_meta',
            field=models.DateField(blank=True, help_text='Fecha límite para alcanzar la meta', null=True),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='meta_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de ahorro u objetivo financiero', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subcuenta',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Propietario directo (para subcuentas independientes)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la subcuenta está activa'),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Color para identificación visual', max_length=7),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Propósito y objetivo de esta subcuenta', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo de la subcuenta', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual en la subcuenta', max_digits=15),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='tipo',
            field=models.CharField(choices=[('tienda_online', 'Tienda Online'), ('tienda_fisica', 'Tienda Física'), ('servicios_profesionales', 'Servicios Profesionales'), ('freelance', 'Trabajo Freelance'), ('negocio_propio', 'Negocio Propio'), ('ingresos_pasivos', 'Ingresos Pasivos'), ('ventas_productos', 'Ventas de Productos'), ('consultoria', 'Consultoría'), ('alquiler_propiedades', 'Alquiler de Propiedades'), ('ahorro_meta', 'Ahorro para Meta'), ('emergencia', 'Fondo de Emergencia'), ('inversion', 'Inversiones'), ('gastos_fijos', 'Gastos Fijos'), ('gastos_variables', 'Gastos Variables'), ('entretenimiento', 'Entretenimiento'), ('viajes', 'Viajes y Vacaciones'), ('educacion', 'Educación y Cursos'), ('salud', 'Salud y Bienestar'), ('familia', 'Gastos Familiares'), ('otros', 'Otros')], default='otros', help_text='Categoría de la subcuenta', max_length=30),
        ),
    ]
