# Generated by Django 5.2 on 2025-07-06 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_subcuenta_es_negocio_subcuenta_fecha_meta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcuenta',
            name='id_cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta principal (opcional para subcuentas independientes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='cuentas.cuenta'),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Propietario directo (requerido para subcuentas independientes)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransferenciaCuentaPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito hacia cuenta principal'), ('retiro', 'Retiro hacia subcuenta')], default='deposito', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_desde_subcuentas', to='cuentas.cuenta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_cuenta_principal', to='cuentas.subcuenta')),
            ],
            options={
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
