# Generated by Django 5.2 on 2025-07-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('documento_identidad', models.CharField(max_length=25)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.BigIntegerField()),
                ('pais', models.CharField(blank=True, default='Peru', max_length=100)),
                ('imagen_perfil', models.BinaryField(blank=True, null=True)),
                ('pin_acceso_rapido', models.CharField(default='000000', max_length=6)),
                ('email_verificado', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.moneda')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
