# Generated by Django 5.2 on 2025-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_usuario_id_cuenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="email_verificado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="pin_acceso_rapido",
            field=models.IntegerField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
