# Generated by Django 5.2 on 2025-07-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('plataforma', models.CharField(choices=[('youtube', 'YouTube'), ('udemy', 'Udemy'), ('coursera', 'Coursera'), ('platzi', 'Platzi'), ('otro', 'Otro')], default='youtube', max_length=20)),
                ('url_externa', models.URLField(help_text='Link al curso externo')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen/thumbnail', null=True)),
                ('duracion_estimada', models.CharField(help_text="ej: '2 horas', '10 videos'", max_length=50)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('idioma', models.CharField(default='Español', max_length=20)),
                ('gratis', models.BooleanField(default=True, help_text='¿Es gratuito?')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso Externo',
                'verbose_name_plural': 'Cursos Externos',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='FavoritoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacion_financiera.cursoexterno')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
