# Generated by Django 5.2 on 2025-07-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_habilitado', models.BooleanField(default=True)),
                ('push_habilitado', models.BooleanField(default=True)),
                ('sms_habilitado', models.BooleanField(default=False)),
                ('frecuencia_resumen', models.CharField(choices=[('instant', 'Instantáneo'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='weekly', max_length=20)),
                ('umbral_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('horario_envio', models.TimeField(default='09:00:00')),
                ('dias_anticipacion', models.IntegerField(default=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('categoria', models.CharField(max_length=50)),
                ('modulo_origen', models.CharField(max_length=50)),
                ('objeto_relacionado', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('archivada', 'Archivada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('email_enviado', models.BooleanField(default=False)),
                ('push_enviado', models.BooleanField(default=False)),
                ('sms_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('url_accion', models.URLField(blank=True, null=True)),
                ('etiquetas', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asunto_email', models.CharField(max_length=200)),
                ('plantilla_email', models.TextField()),
                ('plantilla_push', models.TextField()),
                ('plantilla_sms', models.CharField(blank=True, max_length=160)),
                ('variables_disponibles', models.JSONField(default=list)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('critical', 'Crítica'), ('warning', 'Advertencia'), ('info', 'Informativa')], max_length=20)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
