# Generated by Django 5.2 on 2025-07-06 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas_notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillanotificacion',
            name='tipo_notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas_notificaciones.tiponotificacion'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo_notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas_notificaciones.tiponotificacion'),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='tipo_notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas_notificaciones.tiponotificacion'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'estado'], name='alertas_not_usuario_79c26b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['categoria', 'fecha_creacion'], name='alertas_not_categor_e9ea95_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo_notificacion', 'fecha_creacion'], name='alertas_not_tipo_no_e5ffda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionnotificacion',
            unique_together={('usuario', 'tipo_notificacion')},
        ),
    ]
