# Generated by Django 5.2.8 on 2025-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion_financiera', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoexterno',
            name='plataforma',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('udemy', 'Udemy'), ('coursera', 'Coursera'), ('khan_academy', 'Khan Academy'), ('edx', 'edX'), ('platzi', 'Platzi'), ('otro', 'Otro')], default='youtube', max_length=20),
        ),
    ]
