# Generated by Django 5.2.1 on 2025-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AporteMetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_aporte', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['-fecha_aporte'],
            },
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frecuencia_aporte', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoldeAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje_ahorro', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=25)),
                ('categoria', models.CharField(blank=True, help_text='Categoría del movimiento', max_length=25, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_movimiento', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
