<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-30 15:11
=======
# Generated by Django 5.2.1 on 2025-06-10 21:17
>>>>>>> bba8140 (Corrige problemas con migraciones)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('cuentas', '0002_initial'),
=======
        ('cuentas', '0001_initial'),
>>>>>>> bba8140 (Corrige problemas con migraciones)
        ('gestion_financiera_basica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metaahorro',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moldeahorro',
            name='id_meta_ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_financiera_basica.metaahorro'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
