# Generated by Django 5.2 on 2025-07-06 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_initial'),
        ('gestion_financiera_basica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aportemetaahorro',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='metaahorro',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aportemetaahorro',
            name='id_meta_ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='gestion_financiera_basica.metaahorro'),
        ),
        migrations.AddField(
            model_name='moldeahorro',
            name='id_meta_ahorro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_financiera_basica.metaahorro'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
