# Generated by Django 5.2 on 2025-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera_basica', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoría del movimiento', max_length=25, null=True),
        ),
    ]
