# Generated by Django 5.2 on 2025-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera_basica", "0003_movimiento_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimiento",
            name="tipo",
            field=models.CharField(
                choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")], max_length=25
            ),
        ),
    ]
